source $HOME/MemSQL/arcanist/resources/shell/bash-completion
export PATH=$HOME/MemSQL/arcanist/bin:$PATH
export MEMSQL_OPS_CONFIG=/Users/neildahlke/MemSQL/memsql-ops/ntd_config.cnf
export CPATH=/usr/include/sys:/usr/local/Cellar/mysql/5.6.15/include/mysql

# For compiling dbgen
# export CPATH=


# unix
alias ls='ls -Ghv'
alias ll='ls -l'
alias l.='ls -Ad .*'
alias la='ls -A'
alias grep='grep --color -s'
alias df='df -h'
alias du='du'
alias sr='screen -r'

# git
alias gil='git log --graph --abbrev-commit --stat -C --decorate --date=local'
alias gils='git log --graph --abbrev-commit --pretty=oneline -C --decorate --date=local'
alias gis='git status'
alias gid='git diff -C --date=local'
alias giw='git show -C --date=local --decorate'
alias gic='git checkout'
alias gib='git branch'
alias gir='git rebase -i'
alias gih='git stash save'

# crontab
alias crontab="VIM_CRONTAB=true crontab"

# Vim default editor
export EDITOR=vim
