ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"

plugins=(git)

export EDITOR=vim

# Source ZSH Config
. $ZSH/oh-my-zsh.sh
. $HOME/.zsh/config

export PATH=/usr/local/sbin:$PATH
# Put Python 3 on the path
export PATH=$HOME/Library/Python/3.7/bin:$PATH
# Put GoLang on the path
export PATH=/usr/local/go/bin:$PATH
# Define a GOPATH
export GOPATH=$HOME/go
# Include it on our normal PATH
export PATH=$GOPATH/bin:$PATH
# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"
# Add MySQL Client PATH from brew installation
export PATH="/usr/local/opt/mysql-client/bin:$PATH"

# unix
alias ls='ls -Ghv'
alias ll='ls -l'
alias l.='ls -Ad .*'
alias la='ls -A'
alias grep='grep --color -s'
alias df='df -h'
alias sr='screen -r'

# git
alias gil='git log --graph --abbrev-commit --stat -C --decorate --date=local'
alias gils='git log --graph --abbrev-commit --pretty=oneline -C --decorate --date=local'
alias gis='git status'
alias gid='git diff -C --date=local'
alias giw='git show -C --date=local --decorate'
alias gic='git checkout'
alias gipl='git pull'
alias gips='git push'
alias gim='git merge'
alias gib='git branch'
alias gir='git rebase -i'
alias gish='git stash'

# Common
alias hal='ssh hal'
alias memsql='mysql -u root -h 0 --prompt="memsql> "'
alias drive='open ~/Google\ Drive\ File\ Stream/My\ Drive/'
