########
# zsh config
########
ZSH_DISABLE_COMPFIX=true
DISABLE_MAGIC_FUNCTIONS=true
ZSH=$HOME/.oh-my-zsh
# ZSH_THEME="agnoster"
ZSH_THEME="bira"

plugins=(git autojump aws command-not-found docker)

export EDITOR=vim
export HISTCONTROL=ignorespace

# Source ZSH Config
. $ZSH/oh-my-zsh.sh
. $HOME/.zsh/config


########
# PATH "magic"
########
export PATH=/usr/local/sbin:$PATH
# Put Python 3 on the path
export PATH=$HOME/Library/Python/3.7/bin:$PATH
# Put GoLang on the path
export PATH=/usr/local/go/bin:$PATH
export PATH=$PATH:/usr/local/go/bin
# Define a GOPATH
export GOPATH=$HOME
# Include it on our normal PATH
export PATH=$GOPATH/bin:$PATH
# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"
# Add MySQL Client PATH from brew installation
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
# Add specific OpenSSL to PATH
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
# Add Visual Studio Code (code) to PATH
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

########
# Unix
########
alias ls='ls -Ghv'
alias ll='ls -l'
alias l.='ls -Ad .*'
alias la='ls -A'
alias grep='grep --color -s'
alias df='df -h'
alias sr='screen -r'


##########
# Python
##########
alias python='python3'
alias pip='pip3'


##########
# Git
##########
alias gil='git log --graph --abbrev-commit --stat -C --decorate --date=local'
alias gils='git log --graph --abbrev-commit --pretty=oneline -C --decorate --date=local'
alias gis='git status'
alias gid='git diff -C --date=local'
alias giw='git show -C --date=local --decorate'
alias gic='git checkout'
alias gipl='git pull'
alias gips='git push'
alias gim='git merge'
alias gib='git branch'
alias gir='git rebase -i'
alias gish='git stash'
gac() {
  if [[ -z "$1" ]]; then
    echo "Error: Please provide a commit message."
    return 1
  fi

  if [[ -z "$2" ]]; then
    echo "Error: Please provide a branch name."
    return 1
  fi

  git add .
  git commit -m "$1"
  git push origin "$2"
}


##########
# Docker
##########
alias d='docker'


##########
# VSCode
##########
alias code='code-insiders'


##########
# Kubernetes
##########
alias k='kubectl'


########
# Common Aliases
########
alias todo="ag TODO"


########
# Common Functions
########
function killport() { lsof -i TCP:$1 | grep LISTEN | awk '{print $2}' | xargs kill -9 }


########
# Suffix Aliases
########
alias -s md=code
alias -s json=code
alias -s {cs,js,html}=code


########
# Java helpers
########
## jenv management
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# Add Java Home
export JAVA_HOME=$(/usr/libexec/java_home)

# NOTE: `~/.terraform.d/credentials.tfrc.json` must be up to date, and any workspaces added.
alias awstfcpush='doormat --smoke-test || doormat -r && doormat aws -a se_demos_dev --tf-push --tf-organization hc-se-tfe-demo-neil --tf-workspace AWS-PROD-two-tier-tfc-demo-app,AWS-PROD-two-tier-tfc-demo-app-2'

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/boundary boundary


########
# Google
########

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/neildahlke/src/github.com/dahlke/eklhad/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/neildahlke/src/github.com/dahlke/eklhad/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/neildahlke/src/github.com/dahlke/eklhad/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/neildahlke/src/github.com/dahlke/eklhad/google-cloud-sdk/completion.zsh.inc'; fi


########
# Extra
########

# Issues with Puppeteer on MBP w/ Apple Silicon (M1)
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium`
